vim.cmd('source ~/.config/nvim/keys/mappings.vim')
vim.cmd('source ~/.config/nvim/general/settings.vim')

require('config.packer-auto')
require('plugin')
require('theme')
require('nv-nvimtree')
require('nv-dashboard')
require('nv-blamer')
require('nv-gitsigns')
require('lc-rnvimr')
require('lc-treesitter')
require('lc-telescope')
require('lc-colorizer')
require('lc-lspsaga')
require('lc-compe')
--require('config.my_statusline')
require('config.galaxyline')
require('lsp')
require('lsp.jdtls')
require('lsp.lua-ls')

--vim.cmd('source ~/.config/nvim/lua/lsp/jdtls.vim')
vim.cmd('source ~/.config/nvim/vim-script/lc-coc.vim')
